apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-deployment
  labels:
  app: node-js
spec:
  replicas: 10
  selector:
  matchLabels:
  app: node-js
  template:
   metadata:
   labels:
   app: node-js
  spec:
   containers:
   - name: node-js-con
 	  image: nodejs-test:latest
  ports:
	 - name: http-port
    containerPort: 3000
 priorityClassName: high-priority
  env:
    - name: MONGO_URL
      value: mongodb://mongo:27017/dev
   imagePullPolicy: Always