apiVersion: v1
kind: Pod
metadata:
  name: node-js-pod
  labels:
  	app :pod-label
  selector:
    matchLabels:
      app: node-js
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: high-priority