apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-js-replica-set
spec:
  replicas: 7
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - name: ode-js-con
        image: nodejs-test:latest